name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      # ZIP the userAuth Lambda
      - name: ZIP userAuth Lambda
        run: |
          cd terraform/lambda/auth
          zip -r -X ../../auth.zip index.js package.json node_modules/
          cd ../registerUser
          zip -r -X ../../registerUser.zip index.js package.json node_modules/

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Inicializar Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Importar Lambdas existentes (sem falhar se não existirem)
      - name: Terraform Import Lambdas
        working-directory: ./terraform
        run: |
          terraform import aws_lambda_function.auth techchallenge-auth-lambda || echo "Auth Lambda ainda não existe, será criada."
          terraform import aws_lambda_function.register_user techchallenge-register-user-lambda || echo "RegisterUser Lambda ainda não existe, será criada."

      # Validar a configuração Terraform
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Criar plano
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # Aplicar plano automaticamente
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan