name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      # ZIP the userAuth Lambda
      - name: ZIP userAuth Lambda
        run: |
          cd /terraform/lambdas/userAuth
          zip -r ../../auth.zip .

      # ZIP the registerUser Lambda
      - name: ZIP registerUser Lambda
        run: |
          cd /terraform/lambdas/registerUser
          zip -r ../../registerUser.zip .

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Inicializar Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Validar a configuração Terraform
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Criar plano
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # Aplicar plano automaticamente
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan